import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppMachineProvider } from "@/context/AppMachineContext";
import { CartHeader } from "@/components/templates/CartHeader";
import { classNames } from "@/utils/classnames";
import { RouteGuardProvider } from "@/components/templates/RouteGuardProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classNames(inter.className, "bg-slate-200")}>
        <AppMachineProvider>
          <RouteGuardProvider>
            <CartHeader />
            <main className="mx-auto max-w-screen-xl px-6 flex min-h-screen flex-col gap-4 items-center py-12">
              {children}
            </main>
          </RouteGuardProvider>
        </AppMachineProvider>
      </body>
    </html>
  );
}
