import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppMachineProvider } from "@/context/AppMachineContext";
import { CartHeader } from "@/components/templates/CartHeader";
import { classNames } from "@/utils/classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={classNames(inter.className, "mx-auto max-w-screen-lg px-4")}
      >
        <AppMachineProvider>
          <CartHeader />
          {children}
        </AppMachineProvider>
      </body>
    </html>
  );
}
